const fs = require('node:fs');
const path = require('node:path');

const configJsonPath = path.join(__dirname, '../src/config.json');

if (!fs.existsSync(configJsonPath)) {
  console.warn('src/config.json not found. Run: terraform -chdir=terraform output -json > src/config.json');
  process.exit(0);
}

let raw;
try {
  raw = JSON.parse(fs.readFileSync(configJsonPath, 'utf8'));
} catch (err) {
  console.error(`src/config.json is not valid JSON: ${err.message}`);
  console.error('Re-run: terraform -chdir=terraform output -json > src/config.json');
  process.exit(1);
}

// terraform output -json wraps values: { "key": { "value": "...", "type": "..." } }
const get = (key) => (raw[key]?.value ?? raw[key] ?? '');

const config = {
  aws_region: get('aws_region'),
  cognito_identity_pool_id: get('cognito_identity_pool_id'),
};

if (!config.aws_region || !config.cognito_identity_pool_id) {
  console.error('src/config.json is missing aws_region or cognito_identity_pool_id. terraform apply may not have run.');
  process.exit(1);
}

const content = `// Auto-generated by scripts/prebuild.js from src/config.json (terraform output).
// Do not edit manually. Do not commit src/config.json.
const config = ${JSON.stringify(config, null, 2)};

export default config;
`;

fs.writeFileSync(path.join(__dirname, '../src/config.ts'), content);
console.log('src/config.ts generated from terraform output');
