// Auto-generated by scripts/prebuild.js from src/config.json (terraform output).
// Do not edit manually. Do not commit src/config.json.
const config = {
  aws_region: "",
  cognito_identity_pool_id: "",
};

export default config;
